name: Sync GitHub Mirror to SourgeForge
on:
  schedule:
    # Run every Sunday at 00:12
    - cron: '12 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write

jobs:

  sync-with-sourceforge:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Install tools
        run: |
          sudo add-apt-repository ppa:git-core/ppa
          sudo apt-get update
          sudo apt-get -y install git-svn
      - name: Add SVN remote
        run: git svn init --prefix="upstream/" --stdlayout https://svn.code.sf.net/p/sweethome3d/code/
      - name: Fetch from SVN
        run: git svn fetch --log-window-size=5000
      - name: Convert tags
        run: |
          git for-each-ref refs/remotes/upstream/tags/* --format="%(refname)" | \
          cut -d / -f 5 | \
          while read ref ; \
          do \
          git tag "$ref" "refs/remotes/upstream/tags/$ref" ; \
          git update-ref -d "refs/remotes/upstream/tags/$ref" ; \
          done
      - name: Push all SVN branches/tags
        run: git push --tags origin refs/remotes/upstream/*:refs/heads/upstream/*
